#!/usr/bin/env bash

echo "$~/home/Downloads"
mkdir -p 

inotifywait -m -e close_write -e moved_to --format "%f" "$~/home/Downloads" | while read -r filename; do
    mv "$filename" ~/Downloads/...
done
